feat(ci): Update container.yml

diff --git a/.github/workflows/container.yml b/.github/workflows/container.yml
--- a/.github/workflows/container.yml
+++ b/.github/workflows/container.yml
@@ -6,15 +6,39 @@ on:
       version:
         description: "Semantic version of the image"
         type: string
-        required: true
 
 env:
   REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}
 
 jobs:
+  set-version:
+    runs-on: ubuntu-latest
+    outputs:
+      version: ${{ steps.set-version.outputs.version }}
+    steps:
+      - name: "Checkout"
+        uses: actions/checkout@v4
+      - name: "Get and Set version"
+        id: set-version
+        run: |
+          set -s
+          VERSION="${{ inputs.version }}"
+
+          if [ -z "$VERSION" ]; then
+            echo "version=$VERSION" >> $GITHUB_OUTPUT
+          elif [[ -f .release.yml ]]; then
+            pip install yq
+            current_version=$(cat .release.yml | yq -r ".version")
+            echo "version=$current_version" >> $GITHUB_OUTPUT
+          else
+            echo "Failed to find version..."
+            exit 1
+          fi
+
   build-publish-image:
     runs-on: ubuntu-latest
+    needs: [ set-version ]
 
     outputs:
       digest: ${{ steps.build.outputs.digest }}
@@ -48,9 +72,9 @@ jobs:
             # latest / main
             type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
             # SemVer
-            type=semver,pattern={{version}},value=${{ inputs.version }}
+            type=semver,pattern={{version}},value=${{ needs.set-version.outputs.version }}
             # SemVer, major only
-            type=semver,pattern=v{{major}},value=${{ inputs.version }}
+            type=semver,pattern=v{{major}},value=${{ needs.set-version.outputs.version }}
 
       - name: Build Docker image
         uses: docker/build-push-action@v6.7.0
